[package]
org = "nuwantissera"
name = "googleapis_drive"
version = "0.1.20"
authors = ["Ballerina"]
keywords = ["google", "drive", "storage"]
repository = "https://github.com/ballerina-platform/module-ballerinax-googleapis.drive"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true
