[package]
distribution = "slbeta6"
org = "ballerinax"
name = "googleapis.drive"
version = "2.1.0"
export= ["googleapis.drive", "googleapis.drive.listener"]
authors = ["Ballerina"]
keywords = ["Content & Files/File Management & Storage", "Cost/Free", "Vendor/Google"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-googleapis.drive"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
path = "../java-wrapper/build/libs/java-wrapper-2.1.0.jar"
groupId = "org.ballerinalang.googleapis.drive"
artifactId = "java-wrapper"
version = "2.1.0"
