# This is a basic workflow to help you get started with Actions

name: Deployment

on:
  release:
    types: [published]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action/@master
              with:
                  args: pack ./drive
              env:
                  JAVA_HOME: /usr/lib/jvm/default-jvm
                  CLIENT_ID: ${{ secrets.CLIENT_ID }}
                  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
                  REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
            - name: Ballerina Push
              uses: ballerina-platform/ballerina-action/@master
              with:
                  args: push
              env:
                  WORKING_DIR: ./drive
                  JAVA_HOME: /usr/lib/jvm/default-jvm
                  BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN }}
